name: TitanHammerPro
version: 1.0.0
main: dev.blooddev.titanhammer.TitanHammerPro
api-version: '1.21'
author: Blooddev
description: Professional Titan Hammer plugin
website: https://primehost.iq

commands:
  titanhammer:
    description: Main TitanHammer command
    usage: /titanhammer [give|stats]
    aliases: [th, hammer, titan]
    permission: titanhammer.use

permissions:
  titanhammer.use:
    description: Use TitanHammer
    default: true
  titanhammer.give:
    description: Give TitanHammer
    default: op
